//! Spike 692: the payload shapes that cross from Rust to the webview, copied
//! from src-tauri/src/main.rs and acp_wire.rs, with `ts_rs::TS` derived only
//! under `cfg(test)`. The shipped binary would carry no ts-rs code.
#![allow(dead_code)]
use std::collections::BTreeMap;

#[cfg(test)]
use ts_rs::TS;

#[derive(Clone, Copy, serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub enum Primitive { Idle, Walk, Land, Sit, Sleep, React, Talk, Hold, Chase, Jump }

#[derive(Clone, Copy, serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub enum State { Grounded, Falling, Dragged, Perched, Climbing, Asleep }

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct ChatHarness { name: String, login: Option<String>, alive: bool, session: Option<String> }

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct ChatOpening {
    name: String, character: String, configured: bool, enabled: bool,
    harness: Option<ChatHarness>, model: String, host: String, login: Option<String>,
    harness_name: Option<String>, personality: String, instance_prompt: String, prompt_limit: usize,
}

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct ChatReply {
    said: Option<String>, busy: bool, reacting_to: Option<String>, you: bool,
    #[cfg_attr(test, ts(type = "number | null"))]
    at: Option<u64>, error: Option<String>, superseded: bool,
}

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct ChatStatus {
    behavior: Option<String>, primitive: Option<Primitive>, animation: &'static str,
    state: State, happened: Option<&'static str>, facing: i8, asking: bool,
}

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct ChatStatusPush<'a> { status: &'a ChatStatus, #[cfg_attr(test, ts(type = "number | null"))] wake_ms: Option<u64> }

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct Settled { request: String, option: Option<String> }

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct PermissionOption { pub id: String, pub name: String, pub kind: Option<String> }

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct PermissionAsk {
    pub request: String, pub title: Option<String>, pub kind: Option<String>,
    pub content: Vec<String>, pub input: Option<serde_json::Value>,
    pub locations: Vec<String>, pub options: Vec<PermissionOption>,
}

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct SpritePlacement<'a> {
    id: &'a str, character: &'a str, x: i32, y: i32, width: i32, height: i32,
    animation: &'a str, frame_index: usize, mirror: i8, dialogue: Option<String>,
    thinking: bool, bubble: bool, cue: Option<&'static str>,
}

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct Placement<'a> { sprites: Vec<SpritePlacement<'a>>, visible: bool, fade_ms: u32, sound: bool }

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct CharacterArt { art: BTreeMap<String, Vec<String>>, smooth: bool }

#[derive(serde::Serialize)]
#[cfg_attr(test, derive(TS), ts(export))]
pub struct ArtUrls { characters: BTreeMap<String, CharacterArt> }

/// The #706 shape: an internally tagged enum, as form.rs declares FormRow.
#[derive(serde::Serialize)]
#[serde(tag = "type")]
#[cfg_attr(test, derive(TS), ts(export))]
pub enum CompositeControl {
    TextField { id: String, placeholder: String },
    Popup { id: String, options: Vec<String> },
    Button { id: String, title: String },
}

#[cfg(test)]
mod stale_check {
    //! Same shape as form.rs's `both_ai_sources_serialize_to_the_committed_fixtures`
    //! (#729): generate, compare with the committed copy, fail with a diff and
    //! the command that refreshes it.
    use super::*;
    use ts_rs::TS;

    fn generated() -> String {
        let mut out = String::from("// Generated by `cargo test -p ts-rs-proto`; do not edit.\n\n");
        // Every root the webview listens to or invokes; ts-rs pulls dependencies in.
        for decl in [
            Primitive::export_to_string(), State::export_to_string(),
            ChatHarness::export_to_string(), ChatOpening::export_to_string(),
            ChatReply::export_to_string(), ChatStatus::export_to_string(),
            ChatStatusPush::export_to_string(), Settled::export_to_string(),
            PermissionOption::export_to_string(), PermissionAsk::export_to_string(),
            SpritePlacement::export_to_string(), Placement::export_to_string(),
            CharacterArt::export_to_string(), ArtUrls::export_to_string(),
            CompositeControl::export_to_string(),
        ] {
            let decl = decl.expect("ts-rs can describe this type");
            // One file, so drop the per-type `import` lines ts-rs emits.
            for line in decl.lines().filter(|l| !l.starts_with("import ")) {
                out.push_str(line); out.push('\n');
            }
            out.push('\n');
        }
        // Exactly one trailing newline. `end-of-file-fixer` trims anything more, and a
        // fixture the lint rewrites can never match a fresh render.
        out.truncate(out.trim_end().len());
        out.push('\n');
        out
    }

    #[test]
    fn committed_bindings_match_the_rust_structs() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/generated/payloads.d.ts");
        let fresh = generated();
        if std::env::var_os("REFRESH_BINDINGS").is_some() {
            std::fs::create_dir_all(concat!(env!("CARGO_MANIFEST_DIR"), "/generated")).unwrap();
            std::fs::write(path, &fresh).unwrap();
            return;
        }
        let committed = std::fs::read_to_string(path).unwrap_or_default();
        assert_eq!(committed, fresh,
            "generated/payloads.d.ts no longer matches the Rust structs. \
             Run `REFRESH_BINDINGS=1 cargo test` in spike/typescript-692/ts-rs-proto and commit the result.");
    }
}
