#!/usr/bin/env python3
"""Write the README's Harness Support section from the launch table.

The names and the command lines come from `launch()` in
`src-tauri/src/harness.rs` — the table the app dispatches on, and the only
place a Harness is really named. What a probe run proved about each one comes
from `docs/harnesses.toml`, because no code can know a date. This script joins
the two and rewrites the block between the markers in README.md.

Nothing here is hand-maintained, on purpose. ADR-0011 names the failure it is
avoiding on the published site — the Described page, prose claiming to describe
shipped behaviour with no link a build can check — and scopes itself there,
leaving the README as the front door. The hazard carries even though the rule
does not: a support matrix is the worst case of it, confidently wrong about
whether your Harness works. So the two inputs must agree row for row and the
script fails rather than emit a lie.

Pure standard library, like the other generators here.

    python3 scripts/make-harness-table.py          # rewrite the README
    python3 scripts/make-harness-table.py --check  # exit 1 if it has drifted
"""

import difflib
import pathlib
import re
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
LAUNCH_TABLE = ROOT / "src-tauri" / "src" / "harness.rs"
MANIFEST = ROOT / "docs" / "harnesses.toml"
README = ROOT / "README.md"

BEGIN = "<!-- Generated by scripts/make-harness-table.py. Do not edit this table by hand: -->"
GUIDE = "<!-- change docs/harnesses.toml or launch() in src-tauri/src/harness.rs and re-run it. -->"
END = "<!-- End of the generated Harness table. -->"

# The feature matrix, as `manifest key -> column heading`. Every named row must
# fill every one of them; a Harness nobody has probed says `unverified`.
MATRIX = {
    "fresh": "Fresh session",
    "resumed": "Resumed session",
    "load_session": "`loadSession`",
    "mcp": "MCP transport †",
    "auth": "Auth methods ‡",
}
REQUIRED = ("standing", *MATRIX)


def fail(message):
    raise SystemExit(f"make-harness-table: {message}")


def launch_rows():
    """`(name, command)` per named arm of `launch()`, in source order."""
    source = LAUNCH_TABLE.read_text(encoding="utf-8")
    body = re.search(
        r"pub fn launch\(.*?\n\}", source, re.DOTALL
    )  # the whole function, so a match arm elsewhere cannot answer for it
    if not body:
        fail(f"no launch() found in {LAUNCH_TABLE.relative_to(ROOT)}")
    body = body.group(0)

    if "custom =>" not in body:
        fail("launch() no longer has an escape-hatch arm; the manifest claims one")

    parsed = re.findall(r'"([^"]+)"\s*=>\s*\(\s*value,\s*vec!\[([^\]]*)\]', body)
    rows = [(name, " ".join(re.findall(r'"([^"]*)"', argv))) for name, argv in parsed]
    if not rows:
        fail("launch() parsed but named no Harness; the arm syntax must have moved")

    # Every named arm must be one this shape could read. Without this the
    # generator's failure mode is silence: an arm written any other way — a
    # const argv, a helper call — drops that Harness from the table and still
    # exits 0, which is the hand-editing #458 exists to prevent (#457 is the
    # pull request that will add one).
    named = [name for name in re.findall(r'^\s*"([^"]+)"\s*=>', body, re.M)]
    missed = [name for name in named if name not in {row[0] for row in rows}]
    if missed:
        fail(
            f"launch() names {', '.join(missed)} in an arm this script cannot read. "
            "Match the existing `\"name\" => (value, vec![…])` shape, or teach "
            f"{pathlib.Path(__file__).name} the new one."
        )

    # The command is joined from string literals only, so an argv built from a
    # const would silently render as a shorter command line — drift a human
    # would then bake into the README by re-running this.
    for name, argv in parsed:
        remainder = re.sub(r'"[^"]*"', "", argv)
        if remainder.strip(" ,\t\r\n"):
            fail(
                f"{name}'s argv in launch() is not all string literals, so the "
                "command line here would be wrong rather than merely missing."
            )

    return rows


def cells(row, name):
    for key in REQUIRED:
        value = row.get(key, "").strip()
        if not value:
            fail(f"{name} in {MANIFEST.name} is missing {key}")
        if "|" in value:
            fail(f"{name}.{key} contains a pipe, which would break the table")
    return {key: row[key].strip() for key in REQUIRED}


def table(head, body):
    """A Markdown table in the README's existing shape: `|---|` rule, no padding."""
    rows = ["| " + " | ".join(head) + " |", "|" + "|".join(["---"] * len(head)) + "|"]
    return "\n".join(rows + ["| " + " | ".join(row) + " |" for row in body])


def render():
    manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    named = manifest.get("harness", {})
    hatch = manifest.get("escape_hatch")
    if not hatch:
        fail(f"{MANIFEST.name} has no [escape_hatch]")

    launched = launch_rows()
    missing = [name for name, _ in launched if name not in named]
    extra = [name for name in named if name not in dict(launched)]
    if missing:
        fail(f"launch() names {', '.join(missing)}; {MANIFEST.name} does not")
    if extra:
        fail(f"{MANIFEST.name} names {', '.join(extra)}; launch() does not")

    # Every named row is a literal `AI_BUDDY_HARNESS` value and a literal
    # command line, so both are code; the escape hatch is neither.
    rows = [(f"`{name}`", f"`{command}`", cells(named[name], name)) for name, command in launched]
    label, command = hatch.get("label", ""), hatch.get("command", "")
    if not label or not command or "|" in label + command:
        fail("[escape_hatch] wants a label and a command, neither holding a pipe")
    rows.append((label, command, cells(hatch, "escape_hatch")))

    support = table(
        ["Harness", "Command", "Standing"],
        [[name, command, row["standing"]] for name, command, row in rows],
    )
    matrix = table(
        ["Harness", *MATRIX.values()],
        [[name, *(row[key] for key in MATRIX)] for name, _, row in rows],
    )

    return "\n\n".join(
        [
            BEGIN,
            GUIDE,
            support,
            "What they advertise in `initialize` differs enough to change what ai-buddy can do with them:",
            matrix,
            "- † What `initialize` advertised, not what a turn exercised: no probe run "
            "has yet found an `ai-buddy-mcp` binary, so no Harness has called the `speak` "
            "tool (#434).\n"
            "- ‡ `authMethods` is what is *available*, not what is outstanding — an empty "
            "list is no proof a login is unnecessary. Only `session/new` answering "
            "`-32000` is (ADR-0022).",
            END,
        ]
    )


def main():
    check = "--check" in sys.argv[1:]
    readme = README.read_text(encoding="utf-8")
    before, marker, rest = readme.partition(BEGIN)
    _, end_marker, after = rest.partition(END)
    if not marker or not end_marker:
        fail(f"README.md has no generated Harness table; add the {BEGIN} marker")

    updated = before + render() + after
    if updated == readme:
        print("make-harness-table: README Harness table is current")
        return 0
    if not check:
        README.write_text(updated, encoding="utf-8")
        print("make-harness-table: rewrote the README Harness table")
        return 0

    sys.stdout.writelines(
        difflib.unified_diff(
            readme.splitlines(keepends=True),
            updated.splitlines(keepends=True),
            "README.md",
            "generated",
        )
    )
    print("\nmake-harness-table: the README table is stale. Run scripts/make-harness-table.py.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
