#!/usr/bin/env bash
#
# Keep the vendored pstack skills in `.agents/skills/` current.
#
#   scripts/sync-pstack.sh            regenerate the index and the symlinks
#   scripts/sync-pstack.sh --fetch    re-vendor from upstream first
#
# `.agents/skills/` is the one skills directory for this repository, and it
# mixes vendored skills with repo-owned ones such as `verify-ai-buddy`.
# `UPSTREAM.json` records which names came from upstream, and this script
# adds, updates and deletes only those. A directory not on that list is never
# touched.
#
# `.claude/skills` and `.cursor/skills` are symlinks to it, so there is one
# copy of the bytes. Both loaders glob `<dir>/skills/*/SKILL.md`, and the
# symlink sits in the literal prefix of that pattern rather than in what the
# wildcard matches, so it is plain path traversal into a real directory.

set -euo pipefail

REPO=https://github.com/cursor/plugins
BRANCH=main
root=$(git rev-parse --show-toplevel)
cd "$root"

SKILLS=.agents/skills
META=.agents/pstack/UPSTREAM.json

# The vendored names, one per line, read back out of the lock file.
vendored_names() {
  awk '
    /"skills": \[/ { inlist = 1; next }
    inlist && /^[[:space:]]*\]/ { inlist = 0 }
    inlist { gsub(/[ \t",]/, ""); if ($0 != "") print }
  ' "$META"
}

if [ "${1:-}" = "--fetch" ]; then
  tmp=$(mktemp -d)
  # shellcheck disable=SC2064  # expand tmp now, not at trap time
  trap "rm -rf '$tmp'" EXIT

  git clone --quiet --filter=blob:none --sparse --depth 1 -b "$BRANCH" \
    "$REPO" "$tmp/plugins"
  git -C "$tmp/plugins" sparse-checkout set --skip-checks \
    pstack/skills pstack/agents pstack/LICENSE pstack/.cursor-plugin
  up=$tmp/plugins/pstack

  before=$(vendored_names | sort)
  after=$(find "$up/skills" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)

  # Dropped upstream. Only names this script put there are eligible, so a
  # repo-owned skill cannot be removed by an upstream deletion.
  comm -23 <(echo "$before") <(echo "$after") | while read -r gone; do
    [ -n "$gone" ] || continue
    echo "removing $gone (gone from upstream)"
    rm -rf "${SKILLS:?}/$gone"
  done

  while read -r name; do
    [ -n "$name" ] || continue
    rsync -a --delete "$up/skills/$name/" "$SKILLS/$name/"
  done <<< "$after"

  rsync -a --delete "$up/agents/" .agents/agents/
  cp "$up/LICENSE" .agents/pstack/LICENSE

  # Written without jq: the fields wanted are one `git rev-parse`, one line of
  # plugin.json and a directory listing, and this has to run on a bare macOS
  # checkout too.
  sha=$(git -C "$tmp/plugins" rev-parse HEAD)
  version=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' "$up/.cursor-plugin/plugin.json")

  {
    echo '{'
    echo '  "_warning": "Generated by scripts/sync-pstack.sh and .github/workflows/pstack-sync.yml. Do not hand-edit.",'
    echo "  \"repository\": \"$REPO\","
    echo '  "subpath": "pstack",'
    echo "  \"branch\": \"$BRANCH\","
    echo "  \"commit\": \"$sha\","
    echo "  \"plugin_version\": \"$version\","
    echo '  "license": "MIT",'
    echo "  \"synced\": \"$(date -u +%Y-%m-%d)\","
    echo '  "vendored_into": ".agents/skills (skills), .agents/agents (agents)",'
    echo '  "not_vendored": ["docs", "assets", "automations", ".cursor-plugin"],'
    echo '  "_skills": "The skill directories under .agents/skills this file owns. Anything else there is this repository'"'"'s own and is never touched by the sync.",'
    echo '  "skills": ['
    echo "$after" | sed '$ !s/.*/    "&",/; $ s/.*/    "&"/'
    echo '  ]'
    echo '}'
  } > "$META"
fi

# The index. An agent cannot invoke a skill it cannot see, and 47 SKILL.md
# files are too many to read on the chance one fits. One line each, taken from
# the frontmatter `description` the skill already writes for exactly this
# purpose.
{
  echo "# pstack skills"
  echo
  echo "Generated by \`scripts/sync-pstack.sh\`. Do not hand-edit."
  echo
  echo "One line per vendored skill, taken from its frontmatter. They live in"
  echo "\`.agents/skills/\`, alongside skills this repository owns, which are not"
  echo "listed here. None of them is on by default. Apply one when the user names"
  echo "it, by reading \`.agents/skills/<name>/SKILL.md\` and following it."
  echo
  while read -r name; do
    [ -n "$name" ] || continue
    # Most descriptions are one quoted line; `make-bot-ui` folds its over
    # three, so the indented continuation has to be joined back up.
    desc=$(awk '
      /^description:/ {
        sub(/^description:[ \t]*/, "")
        if ($0 ~ /^[>|]/) {
          out = ""
          while ((getline line) > 0) {
            if (line !~ /^[ \t]+/) break
            sub(/^[ \t]+/, "", line)
            out = (out == "" ? line : out " " line)
          }
          print out
        } else {
          print
        }
        exit
      }
    ' "$SKILLS/$name/SKILL.md" | sed 's/^"//; s/"$//; s/\\"/"/g')
    echo "- \`$name\` — $desc"
  done < <(vendored_names)
} > .agents/pstack/SKILLS.md

# Idempotent, and `-n` so a rerun replaces the link rather than creating one
# inside the directory it already points at.
ln -sfn ../.agents/skills .claude/skills
ln -sfn ../.agents/skills .cursor/skills
ln -sfn ../.agents/agents .claude/agents

echo "$(vendored_names | grep -c .) vendored skills in $SKILLS ($(find "$SKILLS" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ') total), symlinked from .claude and .cursor"
