#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034  # scripts/lib/sync-exclusions.sh reads EXCLUDED; shellcheck can't follow a dynamic source path without -x
# Keep the vendored pstack skills, index and symlinks in `.agents/skills/`
# current; `--fetch` re-vendors from upstream first.

# `.agents/skills/` mixes vendored skills with repo-owned ones. `UPSTREAM.json`
# records which names came from upstream and gates only deletion, so a skill
# this repository owns survives an upstream that has never heard of it.

# `.claude/skills` and `.cursor/skills` are symlinks to it. Both loaders glob
# `<dir>/skills/*/SKILL.md`, and a symlink in the literal prefix is plain path
# traversal into a real directory.

set -euo pipefail

REPO=https://github.com/cursor/plugins
BRANCH=main
root=$(git rev-parse --show-toplevel)
cd "$root"

SKILLS=.agents/skills
META=.agents/pstack/UPSTREAM.json

# Names upstream ships that this sync does not vendor, one `name|reason` per
# line. It drives both the skip and the lock file's `excluded` block. Reasons
# go into JSON verbatim, so no double quotes.
EXCLUDED='tdd|Collision. The Matt Pocock engineering set ships a tdd too, and its implement skill calls it by name, so that one wins. .agents/skills is flat and holds one of the two. See .agents/mattpocock/UPSTREAM.json.'

source "$(dirname "${BASH_SOURCE[0]}")/lib/sync-exclusions.sh"

vendored_names() {
  awk '
    /"skills": \[/ { inlist = 1; next }
    inlist && /^[[:space:]]*\]/ { inlist = 0 }
    inlist { gsub(/[ \t",]/, ""); if ($0 != "") print }
  ' "$META"
}

if [ "${1:-}" = "--fetch" ]; then
  tmp=$(mktemp -d)
  # shellcheck disable=SC2064  # expand tmp now, not at trap time
  trap "rm -rf '$tmp'" EXIT

  git clone --quiet --filter=blob:none --sparse --depth 1 -b "$BRANCH" \
    "$REPO" "$tmp/plugins"
  git -C "$tmp/plugins" sparse-checkout set --skip-checks \
    pstack/skills pstack/agents pstack/LICENSE pstack/.cursor-plugin
  up=$tmp/plugins/pstack

  before=$(vendored_names | sort)
  # Upstream's listing drives the rsync; the lock file only records the last
  # sync. Dropping a name from the lock file would not keep it out, which is
  # what `EXCLUDED` is for.
  shipped=$(find "$up/skills" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)
  after=$(comm -23 <(echo "$shipped") <(excluded_names))

  comm -12 <(echo "$shipped") <(excluded_names) | while read -r skipped; do
    [ -n "$skipped" ] || continue
    echo "skipping $skipped (excluded; see the excluded block in $META)"
  done

  # Dropped upstream, or newly excluded. Only names this script put there are
  # eligible, so neither a repo-owned skill nor one the other sync owns can be
  # removed here.
  comm -23 <(echo "$before") <(echo "$after") | while read -r gone; do
    [ -n "$gone" ] || continue
    echo "removing $gone (gone from upstream or excluded)"
    rm -rf "${SKILLS:?}/$gone"
  done

  while read -r name; do
    [ -n "$name" ] || continue
    rsync -a --delete "$up/skills/$name/" "$SKILLS/$name/"
  done <<< "$after"

  # No allowlist here, unlike skills above: `.agents/agents/` is wholly
  # upstream's, so `--delete` over the whole directory is the honest sync. A
  # repo-owned agent written into it would be eaten.
  rsync -a --delete "$up/agents/" .agents/agents/
  cp "$up/LICENSE" .agents/pstack/LICENSE

  # Without jq, so this runs on a bare macOS checkout.
  sha=$(git -C "$tmp/plugins" rev-parse HEAD)
  version=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' "$up/.cursor-plugin/plugin.json")

  {
    echo '{'
    echo '  "_warning": "Generated by scripts/sync-pstack.sh and .github/workflows/pstack-sync.yml. Do not hand-edit.",'
    echo "  \"repository\": \"$REPO\","
    echo '  "subpath": "pstack",'
    echo "  \"branch\": \"$BRANCH\","
    echo "  \"commit\": \"$sha\","
    echo "  \"plugin_version\": \"$version\","
    echo '  "license": "MIT",'
    echo "  \"synced\": \"$(date -u +%Y-%m-%d)\","
    echo '  "vendored_into": ".agents/skills (skills), .agents/agents (agents)",'
    echo '  "not_vendored": ["docs", "assets", "automations", ".cursor-plugin"],'
    echo '  "_excluded": "Names upstream ships that this sync deliberately does not vendor. Generated from EXCLUDED in scripts/sync-pstack.sh.",'
    echo '  "excluded": {'
    excluded_json
    echo '  },'
    echo '  "_skills": "The skill directories under .agents/skills this file owns. Anything else there belongs to the Matt Pocock sync or to this repository and is never touched by this sync.",'
    echo '  "skills": ['
    echo "$after" | sed '$ !s/.*/    "&",/; $ s/.*/    "&"/'
    echo '  ]'
    echo '}'
  } > "$META"
fi

# The index: one line per skill from its frontmatter `description`, so an agent
# can find a skill without reading every SKILL.md.
{
  echo "# pstack skills"
  echo
  echo "Generated by \`scripts/sync-pstack.sh\`. Do not hand-edit."
  echo
  echo "One line per vendored skill, taken from its frontmatter. They live in"
  echo "\`.agents/skills/\`, alongside skills this repository owns, which are not"
  echo "listed here. None of them is on by default. Apply one when the user names"
  echo "it, by reading \`.agents/skills/<name>/SKILL.md\` and following it."
  echo
  while read -r name; do
    [ -n "$name" ] || continue
    # A folded block scalar (`>-`) continues on indented lines; join them.
    desc=$(awk '
      /^description:/ {
        sub(/^description:[ \t]*/, "")
        if ($0 ~ /^[>|]/) {
          out = ""
          while ((getline line) > 0) {
            if (line !~ /^[ \t]+/) break
            sub(/^[ \t]+/, "", line)
            out = (out == "" ? line : out " " line)
          }
          print out
        } else {
          print
        }
        exit
      }
    ' "$SKILLS/$name/SKILL.md" | sed 's/^"//; s/"$//; s/\\"/"/g')
    echo "- \`$name\` — $desc"
  done < <(vendored_names)
} > .agents/pstack/SKILLS.md

# Idempotent, and `-n` so a rerun replaces the link rather than creating one
# inside the directory it already points at.
ln -sfn ../.agents/skills .claude/skills
ln -sfn ../.agents/skills .cursor/skills
ln -sfn ../.agents/agents .claude/agents

echo "$(vendored_names | grep -c .) vendored skills in $SKILLS ($(find "$SKILLS" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ') total), symlinked from .claude and .cursor"
